#!/usr/bin/env bash
# Dsplays info about domain and subdomain.

records ()
{
record="$(dig ${2}.${1} | awk 'NR==14 { print $4 }')"

IP="$(dig ${2}.${1} | awk 'NR==14 { print $5 }')"

echo "The subdomain $2 is a $record record and points to $IP"
}


# Check number of arguments passed to script
if [ "$#" -ne 2 ];
then
    records $1 "www"
    records $1 "lb-01"
    records $1 "web-01"
    records $1 "web-02"
else
    records $1 $2
fi
