#!/usr/bin/env bash
# script that installs nginx on your server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.holbertonschool.com permanent;" /etc/nginx/sites-available/default
sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx start
